### ISSUE TITLE
SY8205_DC-DC need of BS-LX resistor?

### ISSUE THREAD

**Issue by xnoreq** [WeActTC/Product-Images#2]
Hello,

in the schematic of SY8205_DC-DC there is a 100nF capacitor and 10 ohm resistor (R3) between BS and LX pins.

Why is there a 10 ohm resistor?

**Comment by xnoreq** [comment]
Also, have you measured the output voltage ripple? Thanks.

**Comment by WeActStudio** [comment]
1.10 Ω（R3） is the limiting current 2.output voltage ripple is less than 80 mv
